project:
  type: website
  output-dir: docs
  render:
    - "!wafer_images/architecture.md"
    - "**/*.qmd"
    - "**/*.ipynb"

website:
  title: "WaferGuard ML Slides"

format:
  html:
    theme: cosmo