name: waferguard-ml
on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install requirements
      run: |
        pip install poetry==2.2.1
        poetry install --no-root
      shell: bash
    - name: Run linting
      run: |
        poetry run ruff format --check .
        poetry run ruff check .
      shell: bash